name: crowns
channels:
  - defaults
dependencies:
  - python=3.7.6
  - pip:
    - dask==2.9.1
    - rasterio
    - geopandas
    - shapely
    - dask-jobqueue==0.7.0
    - deepforest==0.2.8
    - distributed==2.9.1
    - pytest
    - bokeh
