name: crowns
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.6
  - geopandas
  - pyfor
  - numpy==1.16.4
  - rtree
  - pip
  - pip:
    - dask
    - rasterio
    - comet_ml
    - shapely
    - dask-jobqueue
    - deepforest
    - distributed
    - pytest
    - bokeh
