name: crowns
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - numpy==1.16.4
  - rasterio
  - dask
  - dask-jobqueue
  - distributed
  - pytest
  - pip
  - pip:
    - rasterstats
    - comet_ml
    - deepforest