---
title: "Scaling"
author: "Ben Weinstein"
date: "3/23/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(ggplot2)
library(scales)
library(dplyr)
library(rstanarm)
library(tidybayes)
library(tidyr)
library(stringr)
library(broom)
```

```{r}
df<-read.csv("tile_averages.csv",row.names = 1)
colnames(df)[colnames(df) %in% "X0"]<-"count"

#mean across year
df<-df %>% group_by(Site,geo_index) %>% summarize(count=mean(count))
ggplot(df) + geom_density(aes(x=count)) + facet_wrap(~Site)
```

Estimate total counts by square km for the DeepForest predictions

```{r}
sample_data<-function(df, n=10){
  df[sample(nrow(df),n),]
}

results<-list()
for(y in 1:200){
  subtotal<-list()
for(x in seq(0.01,1,0.1)){
  subtotal[[as.character(x)]]<-df %>% group_by(Site) %>% sample_frac(x) %>% summarize(total=sum(count)) %>% mutate(frac=x)
}
  results[[y]]<-bind_rows(subtotal)
}

results<-bind_rows(results)
#Get sq km
sqkm<-df %>% group_by(Site) %>% summarize(n=n())
results<-merge(results,sqkm)
results<-results %>% mutate(sqkm=floor(frac*n))

#Summarize by fraction
results<-results %>% group_by(Site,sqkm) %>% summarize(mean=mean(total),lower=quantile(total,0.05),upper=quantile(total,0.95))

ggplot(results,aes(x=sqkm,y=mean)) +facet_wrap(~Site,scales="free") + geom_line() + geom_ribbon(aes(ymin=lower,ymax=upper)) + scale_y_continuous(label=comma) + labs(x="Extent (km^2)",y="Tree Count")
```

Estimate total counts from the field data

```{r}
field<-read.csv("/Users/ben/Documents/NEON_crown_maps/Figures/vst_field_data.csv")
field$area<-field$maxCrownDiameter*field$ninetyCrownDiameter

field<-field %>%  filter(!is.na(itcEasting),!str_detect(eventID,"2014"),growthForm %in% c("single bole tree","multi-bole tree","small tree","sapling"),stemDiameter>15) %>% droplevels() %>% filter(height>3|is.na(height)) 

field<-field %>% group_by(individualID) %>% arrange(desc(eventID)) %>% slice(1)
```

How large of trees should we include. Many don't have height measurements.

```{r}
#field %>% filter(siteID %in% results$Site) %>% filter(!is.na(easting)) %>% filter(stemDiameter < 8) %>% ggplot(.,aes(x=height,fill=siteID)) + geom_density(alpha=0.5) 
```

```{r}
#Scaling factor from a 40m plot to 1km tile
scaling=(1000 * 1000) /((20*20)*2)

#TODO plot type? Individual ID for multi-bole?
# plot_totals<-field %>% filter(siteID %in% results$Site) %>% filter(!is.na(itcEasting)) %>% filter(stemDiameter > 7.5) %>% filter(is.na(height)|height>3) %>% group_by(Site=siteID,plotID,eventID) %>% summarize(n=n()) %>% summarize(n=round(mean(n)))

stan_glm <- stan_glm(n~0 + Site,data = plot_totals,family = poisson,cores=4, iter=20000) 
```

```{r}
newdata <- results %>% group_by(Site,sqkm) %>% distinct() %>% dplyr::select(Site,sqkm) %>% filter(Site %in% plot_totals$Site)
  
estimated <- fitted_draws(stan_glm, newdata,draws=2000) %>% mutate(total=(sqkm * .value)*scaling)  %>% group_by(Site,sqkm,.draw) %>% summarize(total=sum(total)) %>% summarize(mean=mean(total),lower=quantile(total,0.05),upper=quantile(total,0.95))

ggplot(estimated,aes(x=sqkm,y=mean)) +facet_wrap(~Site,scales="free") + geom_line() + geom_ribbon(aes(ymin=lower,ymax=upper)) + scale_y_continuous(label=comma) + labs(x="Extent (km^2)",y="Tree Count")

#Combined
results$Data<-c("Remote Sensing")
estimated$Data<-c("Field")
combined<-bind_rows(list(results,estimated))

ggplot(combined,aes(x=sqkm,y=mean,fill=Data)) +facet_wrap(~Site,scales="free") + geom_line(col="black") + geom_ribbon(aes(ymin=lower,ymax=upper),alpha=0.5) + scale_y_continuous(label=comma) + labs(x="Extent (km^2)",y="Tree Count")  + theme_bw()
ggsave("Scaling_all.png",height=10,width=12)

combined %>% filter(Site %in% c("DSNY","TEAK","OSBS","BART","BLAN","SJER","MLBS","HARV","LENO")) %>% ggplot(. ,aes(x=sqkm,y=mean,fill=Data)) +facet_wrap(~Site,scales="free") + geom_line(col="black") + geom_ribbon(aes(ymin=lower,ymax=upper),alpha=0.5) + scale_y_continuous(label=comma) + labs(x="Extent (km^2)",y="Tree Count")  + theme_bw()
ggsave("Scaling_subset.png",height=7,width=10)
```

## Compare total counts

```{r}
combined %>% group_by(Data,Site) %>% filter(sqkm == max(sqkm)) %>% ungroup() %>% pivot_wider(names_from=Data,values_from=c(mean,lower,upper)) %>% ggplot(., aes(x=mean_Field,y=`mean_Remote Sensing`)) + geom_point()  + labs(x="Field",y="Remote Sensing") + ggtitle("Tree Count") + geom_abline(linetype="dashed") + coord_fixed()    + geom_text(aes(label=Site),size=2,hjust=1.1,vjust=1.2) + theme_bw()  + scale_x_continuous(limits=c(0e7,1.74e7),labels=comma) + scale_y_continuous(limits=c(0e7,1.2e7),labels=comma) + geom_errorbarh(aes(xmin=lower_Field,xmax=upper_Field))
ggsave("FullSiteScale.png",height=6,width=9)
```

# Compare distributions

```{r}
#Load data from HPC
f<-list.files(pattern="sampling")
f<-f[str_detect(f,".csv")]
sampling<-bind_rows(lapply(f,read.csv))

#Plot sampling curves
p <- ggplot() + geom_density(data=sampling,aes(x=tree_density,fill=as.factor(year)),alpha=0.4) + facet_wrap(~site,scales="free") + labs(fill="year")

#Get site curve
field_density<-field %>% filter(siteID %in% results$Site) %>% group_by(site=siteID,plotID,eventID) %>% summarize(n=n()) %>% summarize(tree_density=round(mean(n)))

rects<-field_density %>% group_by(site) %>% summarize(mean=mean(tree_density),lower=quantile(tree_density,0.05), upper=quantile(tree_density,0.95))
  
p +geom_rect(data=rects,aes(xmin=lower,xmax=upper,ymin=0,ymax=Inf),fill="black",alpha=0.2) + geom_vline(data=rects,aes(xintercept=mean),linetype="dashed") + theme_bw() + labs(x="Trees per plot",fill="Year")
ggsave("sampling3.png",height=4,width=7)

rect_subset <- rects %>% filter(site %in% c("DSNY","TEAK","OSBS","BART","DELA","SJER","JERC","HARV","LENO"))
sampling %>% filter(site %in% c("DSNY","TEAK","OSBS","BART","DELA","SJER","JERC","HARV","LENO")) %>% group_by(site) %>% filter(year==max(year)) %>% ggplot(.) + 
geom_density(aes(x=tree_density),fill="black",alpha=0.4) + facet_wrap(~site,scales="free") +geom_rect(data=rect_subset,aes(xmin=lower,xmax=upper,ymin=0,ymax=Inf),fill="black",alpha=0.2) + geom_vline(aes(xintercept=mean(tree_density))) + geom_vline(data=rect_subset,aes(xintercept=mean),linetype="dashed") + theme_bw() + labs(x="Trees per plot")
ggsave("Sampling_subset.png",height=4,width=7)

#as a pair of distributions
field_density$data<-c("NEON Field Plots")
sampling$data<-c("Simulated RS Plots")
combined<-bind_rows(field_density,sampling) %>% filter(site %in% c("DSNY","TEAK","OSBS","BART","DELA","SJER","JERC","HARV","LENO")) %>%
ggplot(.,aes(x=tree_density,fill=data)) + geom_density(alpha=0.3) + facet_wrap(~site,scales="free") + labs(x="Trees per plot")
combined
ggsave("Sampling_distributions.png",height=4,width=7)
```
